# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b5fece3608eb154ff4a204638b2cf690d760f915bcff277aaeb8873ae03c57d9a310ff413669f6bba67c187ffefab953f2274318c4eb34f47c63d3249a00427

test:
  secret_key_base: fa80408ae73affc08427a6b435f01f9423ac92c105d774eb3cc3195a745d8f465ddc1bc70f978985a5ba382d5406788e0e826dc899af6fca8945450034e5696f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
